version: '3.9'

services:
  web:
    build: .
    restart: always
    ports:
      - "8923:8923"
    volumes:
      - .:/ecolbetPay
    image: web:ecolbetPayApi_image
    environment:
      - SECRET_KEY=${SECRET_KEY}
    env_file:
      - .env
    container_name: ecolbetPayApi_container
    command: gunicorn --bind 0.0.0.0:8923 ecolbetPay.wsgi:application
